[book]
title = "企业架构设计方法与实践"
authors = ["Tony Deng"]
language = "zh-CN"
multilingual = false
src = "."

[output.html]
additional-css = ["theme/simple-lightbox.css", "theme/theme.css"]
additional-js = ["theme/simple-lightbox.min.js","theme/theme.js"]

[build]
build-dir = "_book"