name: mdbook deploy github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup Pages
        id: pages
        uses: actions/configure/pages@v4
          
      - name: Build with mdBook
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
  deploy: 
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
